# Generated by Django 4.2.1 on 2023-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='student_photo.jpg', upload_to='student_photo/'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(default='tutor_photo.jpg', upload_to='tutor_photo/'),
        ),
    ]
