# Generated by Django 4.2.1 on 2023-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_photo_tutor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='student_photo.png', upload_to='student_photo/'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(default='tutor_photo.png', upload_to='tutor_photo/'),
        ),
    ]
