# Generated by Django 4.2.1 on 2023-05-22 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_student_id_tutor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='id',
        ),
    ]
